### ISSUE TITLE
`--strict` doesnt work with autoOpt

### ISSUE THREAD

**Issue by Tony-xy-Liu** [hallamlab/SABer#24]
cmd:

> singularity run ./saber-master.sif \
>     saber recruit -t 4 \
>     -l ./read_list.txt \
>     -m ./SRR10053317.asm.fa \
>     -s ./SRR10053317_bin00.fa \
>     -o ./saber_test

std out:

> Loading/Building subcontigs for Metagenomes: 1
> File specified, processing SRR10053317_bin00.fa
> Starting MinHash Recruitment
> MinHash already done
> Cleaning up intermediate files...
> MinHash Recruitment Algorithm Complete
> Starting Abundance Data Transformation
> Building SRR10053317.asm abundance matrix
> Raw reads in interleaved file...
> Running minimap2-sr on SRR10053317
> Converting SAM to BAM with SamTools
> Sort BAM with SamTools
> Cleaning up intermediate files...
> 
> Calculating Coverage with jgi_summarize_bam_contig_depths
> Cleaning up intermediate files...
> Starting Tetranucleotide Data Transformation
> Calculating tetramer Hz matrix for SRR10053317.asm
> Running AutoOpt to find optimal hyperparameters
> Loading Reference Renyi Entropy profiles
> Calculating Renyi Entropy profile
> 100%|█████████████████████████████████████████████| 8/8 [00:00<00:00, 57.06it/s]
> AutoOpt method: algo_defaults
> Parameter set: Strict
> 	De Novo min_cluster_size: 50
> 	De Novo min_samples: 15
> 	Anchored min_cluster_size: 150
> 	Anchored min_samples: 5
> 	Anchored nu: 0.6
> 	Anchored gamma: 0.1
> Traceback (most recent call last):
>   File "/opt/conda/envs/saber_cenv/bin/saber", line 8, in <module>
>     sys.exit(main())
>   File "/opt/conda/envs/saber_cenv/lib/python3.7/site-packages/saber/__main__.py", line 45, in main
>     cmd(sys.argv[2:])
>   File "/opt/conda/envs/saber_cenv/lib/python3.7/site-packages/saber/commands.py", line 141, in recruit
>     clusters = clst.runClusterer(mg_id, save_dirs_dict[recruit_s.mode], save_dirs_dict[recruit_s.mode],
> KeyError: 'strict'
>

**Comment by RyloByte** [comment]
Hey Tony,
Thanks for the message.  I have rebuilt the docker recently.
Could you rebuild the singularity SIF and give it another test?
`singularity pull docker://quay.io/hallamlab/saber`
Let me know how it goes.
Ryan

**Comment by RyloByte** [comment]
I think I have fixed this with some recent pushes to master
