### ISSUE TITLE
Permission Error when installing saber

### ISSUE THREAD

**Issue by zcaiElvis** [hallamlab/SABer#6]
When executing 

`python3 setup.py sdist bdist_wheel `

I got permission error: 

> error: [('build/bdist.linux-x86_64/wheel/SABerML-0.0.1-py3.8.egg-info', 'build/bdist.linux-x86_64/wheel/SABerML-0.0.1.dist-info', "[Errno 13] Permission denied: 'build/bdist.linux-x86_64/wheel/SABerML-0.0.1.dist-info'")].

Previous installation processes have all been successfully completed.

**Comment by RyloByte** [comment]
Hey thanks for helping debuggin. Can you give me some details:
1. What is your OS?
2. What is your Python version?
3. What is your pip version?
4. Did you install in a conda env as suggested in the README?

**Comment by zcaiElvis** [comment]
Sorry, should have mentioned earlier.

1. Windows 10 running Windows Subsystem for Linux (Ubuntu 18.04.3)
2. Python 3.8.3
3. Pip 20.0.2
4. Yes, I ran everything inside the conda environment

**Comment by zcaiElvis** [comment]
Fixed by installing on Ubuntu 20.04
